services:
  api:
    build: 
      context: ./
      target: prod
    restart: always
    depends_on:
      - backend
    env_file: ./api.env
    ports:
      - "8080:9090"
    volumes:
      - ./src:/usr/dockerapp/src
  backend:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: monsters
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: