services:
  api:
    build: .
    ports:
      - 9090:9090
  backend:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: test_db
      ports:
      - 3307:3306
      expose:
        3306
    volumes:
      -db-data:/dbs/mysql

volumes:
  db-data: